name: Build
on: [push]
jobs:
  node-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodeVersion:
          - 14
          - 16
          - 18
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{runner.OS}}-build-node_${{ matrix.nodeVersion }}-${{hashFiles('yarn.lock')}}
          restore-keys: |
            ${{runner.OS}}-build-node_${{ matrix.nodeVersion }}-*
      - run: |
          cd node
          yarn install
      - run: |
          cd node
          yarn test

  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.0' # The Go version to download (if necessary) and use.
      - run: go version
      - run: go test -v github.com/jc-lab/jclab-prs-2301/engine
